repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: hollow-toolbox
  description: Shared golang packages for the hollow ecosystem
  homepage: https://hollow.sh/
  private: false
  has_issues: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true

# Labels: define labels for Issues and Pull Requests
# labels:
#   - name: bug
#     color: CC0000
#   - name: feature
#     color: 336699
#   - name: first-timers-only
#     # include the old name to rename and existing label
#     oldname: Help Wanted

teams:
  - name: hollow-core
    permission: push

branches:
  - name: main
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams:
            - hollow-core
      required_status_checks:
        strict: false
        contexts: []
      enforce_admins: true
      required_linear_history: true
      # Don't allow anyone to push directly to the branch
      restrictions: null
